namespace Parser;

public enum TokenType
{
    LEFT_PAREN, RIGHT_PAREN, 
    LEFT_BRACE, RIGHT_BRACE, //{}
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    
    IDENTIFIER, STRING_LITERAL, NUMBER_LITERAL,
    
    AND, CLASS, ELSE, FALSE, FUNCTION, FOR, IF, NULL, OR, PRINT, RETURN, SUPER, THIS, TRUE, VAL, WHILE, MUT, //reserved keywords
    
    EOF
}